### PR TITLE
point to sd-bus on github in README

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zonque** [comment]
Thanks for the patch, looks good.

However, patches that are merged into this repository will end up verbatim in the kernel upstream, so we need to enforce the kernel rules. Please reformat the patch subject to "kdbus: doc: update sd-bus URL" or something and add a Signed-off-by line. Thanks!

**Comment by ghost** [comment]
You're totally right. I'm going to actually clone this and give it a real branch name then too.

**Comment by ghost** [comment]
none of the other patch subjects seem to mention kdbus though?

**Comment by zonque** [comment]
Yeah, you're right. Guess that's gonna be fixed up when the patches are exported eventually. Anyway, the Signed-off-by is needed :)

**Comment by ghost** [comment]
did that in #2

**Pull request closed without merging**
